### ISSUE TITLE
DMSF module ERROR

### ISSUE THREAD

**Issue by monstrfolk** [hicknhack-software/redmine_hourglass#20]
Started GET "/projects/XXXXX/settings" for 67.188.13.138 at 2017-05-30 03:05:34 -0400
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"XXXXX"}
  Current user: admin (id=1)
  Rendered projects/settings.html.erb within layouts/base (154.3ms)
Completed 500 Internal Server Error in 175ms (ActiveRecord: 5.3ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x00000004fe5de0>:0x007f6921ca3730>
Did you mean?  project_settings_tabs_with_dmsf):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/projects_helper_patch.rb:7:in `project_settings_tabs'
  plugins/redmine_messenger/lib/redmine_messenger/patches/projects_helper_patch.rb:15:in `project_settings_tabs_with_messenger'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/projects_helper_patch.rb:7:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___968604322157017615_40916400'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by arBmind** [comment]
Sorry for your bad experience.
It seems that the issue is related to incompatible plugins. (Here "redmine_messenger")

More specifically Redmine lacks the support for project based settings of plugins. Some plugin need it, so they create a hack for that. If those hacks of multiple plugins collide, it all falls down.

I hope we can fix this issue, but it seems to be related to the use of now deprecated Ruby features. So it will most likely involve a patch to the redmine_messenger plugin. Meanwhile we should raise the pressure on Redmine to support project based settings for plugins.

**Comment by monstrfolk** [comment]
This is cause of dmsf plugin (https://github.com/danmunn/redmine_dmsf)

I got this plugin working with it by changing project_settings_tabs to project_settings_tabs_with_dmsf.

**Comment by jume-dev** [comment]
I made a pull request here: https://github.com/danmunn/redmine_dmsf/pull/729

Otherwise there is nothing we can do here

**Comment by jume-dev** [comment]
Actually i found a way to make it work regardless of that pull request (which was rejected anyway). Going to fix it in a few minutes
